#!/usr/bin/env bash
# display content of the file /etc/passwd

passwd_file="/etc/passwd"

if [ -e "$passwd_file" ]; then
  while IFS=: read -r username password uid gid gecos home shell; do
	  echo "The user $username (UID: $uid) is part of the group $gid gang,"
    echo "lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $password,"
    echo "more info about the user here: $gecos"
    echo
  done < "$passwd_file"
else
  echo "Error: /etc/passwd file does not exist."
fi
