#!/usr/bin/env bash
# commands to install HAproxy successfully
sudo apt-get update
sudo apt-get install -y haproxy=2.6.\*

server_config=\
"
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 240687-web-01 35.153.231.146:80 check
    server 240687-web-02 54.210.59.168:80 check
"

sudo echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
