#!/usr/bin/env bash
# install haproxy
sudo apt-get update
sudo apt-get install -y haproxy
sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    maxconn 4096
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 240687-web-01 35.153.231.146:80 check
    server 240687-web-02 54.210.59.168:80 check
EOL

sudo systemctl daemon-reload
sudo systemctl enable haproxy

