#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

PRID=$$
echo "$PRID" > /var/run/holbertonscript.pid

function sigint_handler()
{
    echo "Y U no love me?!"
}

function Quit_and_kill()
{
    echo "I hate the kill command"
    rm -f /var/run/holbertonscript.pid
    kill -9 $PRID
}

trap sigint_handler SIGINT
trap Quit_and_kill SIGQUIT SIGTERM

while :
do
    echo "To infinity and beyond"
    sleep 2
done
